
package com.soapservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloGeneratorService", targetNamespace = "http://revature.com/", wsdlLocation = "http://localhost:9002/SOAPService/jaxws/hello?wsdl")
public class HelloGeneratorService
    extends Service
{

    private final static URL HELLOGENERATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOGENERATORSERVICE_EXCEPTION;
    private final static QName HELLOGENERATORSERVICE_QNAME = new QName("http://revature.com/", "HelloGeneratorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9002/SOAPService/jaxws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOGENERATORSERVICE_WSDL_LOCATION = url;
        HELLOGENERATORSERVICE_EXCEPTION = e;
    }

    public HelloGeneratorService() {
        super(__getWsdlLocation(), HELLOGENERATORSERVICE_QNAME);
    }

    public HelloGeneratorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOGENERATORSERVICE_QNAME, features);
    }

    public HelloGeneratorService(URL wsdlLocation) {
        super(wsdlLocation, HELLOGENERATORSERVICE_QNAME);
    }

    public HelloGeneratorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOGENERATORSERVICE_QNAME, features);
    }

    public HelloGeneratorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloGeneratorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloGenerator
     */
    @WebEndpoint(name = "HelloGeneratorPort")
    public HelloGenerator getHelloGeneratorPort() {
        return super.getPort(new QName("http://revature.com/", "HelloGeneratorPort"), HelloGenerator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloGenerator
     */
    @WebEndpoint(name = "HelloGeneratorPort")
    public HelloGenerator getHelloGeneratorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://revature.com/", "HelloGeneratorPort"), HelloGenerator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOGENERATORSERVICE_EXCEPTION!= null) {
            throw HELLOGENERATORSERVICE_EXCEPTION;
        }
        return HELLOGENERATORSERVICE_WSDL_LOCATION;
    }

}
